# Generated by Django 2.2.7 on 2019-11-14 12:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('category', models.CharField(choices=[('0', 'standard'), ('1', 'Apartmant'), ('2', 'Business'), ('3', 'De luxe'), ('4', 'President')], max_length=1)),
                ('number_room', models.IntegerField()),
                ('bed1', models.UUIDField(default=uuid.uuid4)),
                ('bed2', models.UUIDField(default=uuid.uuid4)),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
    ]
