# Generated by Django 2.2.7 on 2019-11-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='bed2',
        ),
    ]
