# Generated by Django 2.2.5 on 2019-10-18 20:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NukeList',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nps_name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('factor', models.IntegerField()),
            ],
        ),
    ]
