# Generated by Django 2.2.5 on 2019-11-15 12:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('number_room', models.IntegerField()),
                ('room_id', models.UUIDField(default=uuid.uuid4)),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
    ]
