# Generated by Django 2.2.7 on 2019-12-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='room_id',
            field=models.UUIDField(),
        ),
    ]
