# Generated by Django 3.0.1 on 2020-01-03 19:56

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0003_auto_20191205_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='number_room',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='guests',
            name='room_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
