# Generated by Django 2.2.7 on 2019-11-25 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='guest',
        ),
    ]
